# simple test from "CI/CD for Machine Learning Course" - https://www.wandb.courses/courses/ci-cd-for-machine-learning

on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print([i for i in os.getenv('MY_VAR')])
      shell: python
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
